name: Deploy to Surge

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository  
        uses: actions/checkout@v2

      - name: Install Surge 
        run: npm install --global surge

      - name: Deploy to Surge  # Added hyphen for steps
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          surge ./ --domain eliandomaintest.surge.sh
